# Start with the latest Dockerhub image for Node.js
# This image is built on Debian Linux
FROM node:latest

# Copy the Node.js project into the container
COPY helloworld/ /helloworld/

# Set the default command for this Docker container
CMD node /helloworld/index.js
